version: '3.9'
services:
  db:
    image: postgres:15.3-alpine
    restart: always
    ports:
      - '5432:5432'
    expose:
      - '5432'
    env_file:
      - ./.env
    volumes:
      - db:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
  api:
    container_name: financial-api
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 5000:5000
    env_file:
      - ./.env
    links:
      - db
volumes:
  db:
    driver: local
